### ISSUE TITLE
Error: TypeError: mockServer.init is not a function

### ISSUE THREAD

**Issue by ferryarman** [getdock/pptr-mock-server#14]
Hi,

I was trying to use your library to do the Puppeteer API mocking. But, I encountered this issue. 
Any clue ? Thanks.
```
const mockServer = require('pptr-mock-server')

class Portal {
   async launchBrowser() {
     const baseAppUrl = 'https://cnc-api-dev.localz.io'
     this.mockRequest = await mockServer.init(this.page, {
        baseAppUrl,
        baseApiUrl: baseAppUrl + '/v1/api/'
     })

     const responseConfig = { body: {result: 'ok'} };
     this.mockRequest.get('api', 200, responseConfig);
   }
}
```
```
Error: TypeError: mockServer.init is not a function
```
This is the package version I'm using.
"pptr-mock-server": "^1.0.0"

**Comment by ermakovich** [comment]
I believe this is because there is no backward compatibility right now for CommonJS modules (`require`). Try to import using ES6 `import` syntax. I.e. `import mockServer from 'pptr-mock-server'.

**Comment by ferryarman** [comment]
Thanks for your reply. 

I think I managed to resolve the ES6 `import` issue by replacing `cucumber-js` with `jest-cucumber` & `jest-puppeteer` combination.

**Comment by ermakovich** [comment]
I'm not familiar with `jest-cucumber` and `jest-puppeter` unfortunately, and I'm not sure on your exact setup, but if you use Babel you should be able to use `cucumber-js` as well. Here is how we use it in our projects:
https://github.com/getdock/dev-configs/blob/master/cucumber.js

**Comment by ferryarman** [comment]
Thanks @ermakovich for your tips.

I have tested using your recommended config, but encountered with babel's incompatible version
```
Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "~/node_modules/@babel/preset-env/lib/index.js")
```
I guess, for now I'll stick with `jest-cucumber` + `jest-puppeteer` combination & your `pptr-mock-server` libraries :) If I have spare time, I'll play around again with `cucumber-js` way.

**Comment by ermakovich** [comment]
Ok, do not hesitate to create new issue if you have any questions. I feel like documentation/examples need to be improved a bit :)
